CREATE datebase communitymanagement

CREATE TABLE activity(
  address VARCHAR(255) NOT NULL,
  checkinNo INT(11) DEFAULT 0,
  credits INT(11) DEFAULT 100,
  description VARCHAR(255) NOT NULL,
  durationTime FLOAT(30) NOT NULL,
  grabTime DATE,
  holdTime DATE NOT NULL,
  id INT(11) NOT NULL UNIQUE,
  lid INT(11),
  limits INT(11) NOT NULL,
  lname VARCHAR(255) ,
  NAME VARCHAR(255) NOT NULL,
  oid INT(11) NOT NULL,
  oname VARCHAR(255) NOT NULL,
  pubtime DATE,
  astate INT,
  isApply BOOLEAN,
  PRIMARY KEY(id)
) 
CREATE TABLE lecturer(
  id INT(11) NOT NULL,
  NAME VARCHAR(255)NOT NULL,
  PASSWORD VARCHAR(255)NOT NULL,
  phone VARCHAR(255)NOT NULL,
  qualified BOOLEAN NOT NULL,
  community VARCHAR(255) NOT NULL,
  credits INT(11) DEFAULT 0,
  RESUME VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
)
CREATE TABLE lhistory(
	aid INT(11) NOT NULL,
	lid INT(11) NOT NULL UNIQUE,
	aname VARCHAR(255) NOT NULL,
	lname VARCHAR(255) NOT NULL,
	PRIMARY KEY(lid)
)
CREATE TABLE organizer(
	community VARCHAR(255) NOT NULL,
	id INT(11) NOT NULL UNIQUE,
	NAME VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	phone VARCHAR(255) NOT NULL,
	flag INT(11) NOT NULL,
	PRIMARY KEY(id)
)
CREATE TABLE participation(
	aid INT(11) NOT NULL UNIQUE,
	aname VARCHAR(255) NOT NULL,
	isSign BOOLEAN ,
	sid INT(11) NOT NULL,
	sname VARCHAR(255) NOT NULL,
	PRIMARY KEY(aid)
)

CREATE TABLE root(
  id INT(11) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
)
CREATE TABLE student( 
  id INT(11) NOT NULL UNIQUE,
  NAME VARCHAR(255) NOT NULL,
  PASSWORD INT(11) NOT NULL,
  credits INT(11) DEFAULT 0,
  phone VARCHAR(255) NOT NULL,
  address VARCHAR(244) NOT NULL,
  PRIMARY KEY(id)
)


