CREATE TABLE lecturer(
  id INT(11) NOT NULL,
  NAME VARCHAR(255)NOT NULL,
  PASSWORD VARCHAR(255)NOT NULL,
  phone VARCHAR(255)NOT NULL,
  qualified BOOLEAN NOT NULL,
  community VARCHAR(255) NOT NULL,
  credits INT(11) DEFAULT 0,
  RESUME VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
)
