CREATE TABLE student( 
  id INT(11) NOT NULL UNIQUE,
  NAME VARCHAR(255) NOT NULL,
  PASSWORD INT(11) NOT NULL,
  credits INT(11) DEFAULT 0,
  phone VARCHAR(255) NOT NULL,
  address VARCHAR(244) NOT NULL,
  PRIMARY KEY(id)
)
